const LOAD_PRODUCTS = "LOAD_PRODUCTS";
const FILTER_PRODUCTS = "FILTER_PRODUCTS";
const UPDATE_FILTERS = "UPDATE_FILTERS";
const SORT_PRODUCTS = "SORT_PRODUCTS";

export { LOAD_PRODUCTS, FILTER_PRODUCTS, UPDATE_FILTERS, SORT_PRODUCTS };

